In [9]:

"""#TO accessing the data base 




#to create data base and manipulate also



#to create Data base:-pd.Dataframe




import pandas as pd



#used as a data analytical tool



python Data analytical library





#FEAUTURES OF Pandas
   fast  and efficient
   reshaping and pivoting data
   slice a large data 
   add and deleting data
   time series functionality
   we can use grouping
   
   
TO install in pip and conda
#pip install pandas
#conda install-c anaconda pandas


TO CHECK installation
type import pandas if no error then its well and good


Pandas- series
Series is a one dimensional array like structure with homogeneous
collection of single data types

if its combained more than one data type its called objected series
 it have indexes and data values
 by default start from 0


pandas.series(data,indes,dtype,copy)



CREAATION OF SERIES
 Empty series
 array
 dictionary
 scalar values of constants
 
Empty series
"""
import pandas as pd
pd.Series

#create from numpy arrays
import numpy as np
data =np.array([10,20,30,40,50])
data
   
#creatind Data fro arrays

pandas.core.series.Series

In [12]:
#creatind Data fro arrays without indexing
pd.Series(data = data)

0    10
1    20
2    30
3    40
4    50
dtype: int32

In [13]:
#with index
pd.Series(data=data,index =range(1,6))

1    10
2    20
3    30
4    40
5    50
dtype: int32

In [14]:
#to change the data type 
pd.Series(data=data,index = range(1,6),dtype ='float')

1    10.0
2    20.0
3    30.0
4    40.0
5    50.0
dtype: float64

In [16]:
#from dicrionary #keys are rows and values are values 


#more than argments theows  NAN
d ={'a':100,'b':200,'c':300}
pd.Series(data=d,index=['a','b','c'])

a    100
b    200
c    300
dtype: int64

In [18]:
#SCALAR VALUES

pd.Series([1,2,3,4,5])


0    1
1    2
2    3
3    4
4    5
dtype: int64

In [20]:
#DAta Frame 
#empty 

df = pd.DataFrame
df

pandas.core.frame.DataFrame

In [21]:
#from list create a data frame

data =[1,2,3,4,5,6,7,8]
pd.DataFrame(data)



0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8

In [24]:
data =[1,2,3,4,5,6,7,8]
df = pd.DataFrame(data,columns =['id'])
df


id
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8

In [25]:
#from nested list

data =[['ravi',100],['guna',200],['garun',300]]
df = pd.DataFrame(data,columns =['names','age'])
df


names  age
0   ravi  100
1   guna  200
2  garun  300

In [27]:
#from Dictionary #keys coloumns and values as per coloumns


data ={'names':['ravi','guna','partha','mathan'],'age':[28,24,29,42]}
df = pd.DataFrame(data,columns =['names','age'])
df


names  age
0    ravi   28
1    guna   24
2  partha   29
3  mathan   42

In [ ]:
#Itreation in pandas


@iteritems-iterate over the (key,value) pairs


@iterrows  -itreate over the rows as (index,series)pairs


@itertuples -itreates over the rows as named tuple



In [31]:
import pandas as pd
import numpy as np
data =[10,20,30,40,50]
df = pd.Series(data)
df

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [32]:
#seires iterate

for x in data:
    print(x)

10
20
30
40
50


In [33]:
for x in df:
    print(x)

10
20
30
40
50


In [62]:
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack',
   'Lee','David','Gasper','Betina','Andres']),
   'Age':pd.Series([25,26,25,23,30,29,23,34,40,30,51,46]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,3.78,2.98,4.80,4.10,3.65])
}
columns =['Name','Age','Rating']
df =pd.DataFrame(d)
df

Name  Age  Rating
0      Tom   25    4.23
1    James   26    3.24
2    Ricky   25    3.98
3      Vin   23    2.56
4    Steve   30    3.20
5    Smith   29    4.60
6     Jack   23    3.80
7      Lee   34    3.78
8    David   40    2.98
9   Gasper   30    4.80
10  Betina   51    4.10
11  Andres   46    3.65

In [49]:
#Series Basic Functionality

data =np.random.randn(10)
data
df  =pd.Series(data)
df





0   -0.273052
1   -1.087616
2   -2.033335
3   -0.693010
4    1.000762
5   -1.934345
6    0.416332
7   -0.813588
8    0.274292
9   -0.437675
dtype: float64

In [50]:
#AXES -return index values
df.axes


[RangeIndex(start=0, stop=10, step=1)]

In [51]:
#dtype
df.dtype

dtype('float64')

In [52]:
#emppty
df.empty

False

In [53]:
#ndim
df.ndim

1

In [54]:
#size - nof elements

df.size

10

In [55]:
#Values -empty array

df.values

array([-0.27305241, -1.08761602, -2.03333487, -0.69300951,  1.00076229,
       -1.93434478,  0.41633182, -0.8135881 ,  0.27429245, -0.43767542])

In [61]:
#Head -top values


df.head()
df.head(2)

0   -0.273052
1   -1.087616
dtype: float64

In [60]:
#tail -bottom values


df.tail()
df.tail(2)

8    0.274292
9   -0.437675
dtype: float64

In [63]:
#DATA FRAAME BASIC FUNCTIONALITY

d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack',
   'Lee','David','Gasper','Betina','Andres']),
   'Age':pd.Series([25,26,25,23,30,29,23,34,40,30,51,46]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,3.78,2.98,4.80,4.10,3.65])
}
df =pd.DataFrame(d)
df
 

Name  Age  Rating
0      Tom   25    4.23
1    James   26    3.24
2    Ricky   25    3.98
3      Vin   23    2.56
4    Steve   30    3.20
5    Smith   29    4.60
6     Jack   23    3.80
7      Lee   34    3.78
8    David   40    2.98
9   Gasper   30    4.80
10  Betina   51    4.10
11  Andres   46    3.65

In [64]:
#axes-details about the given data

df.axes

[RangeIndex(start=0, stop=12, step=1),
 Index(['Name', 'Age', 'Rating'], dtype='object')]

In [66]:
#dtypes-type of elements


df.dtypes


Name       object
Age         int64
Rating    float64
dtype: object

In [67]:
#ndim-dimension

df.ndim

#series dimension -1 data frame dimension -2

2

In [68]:
#Size-returns size\


df.size

36

In [72]:
#head -top elements

df.head(2)

Name  Age  Rating
0    Tom   25    4.23
1  James   26    3.24

In [73]:
#tail -low elements

df.tail(2)

Name  Age  Rating
10  Betina   51    4.10
11  Andres   46    3.65

In [74]:
#T-transforce using for matrix and vectoe operations transfers rows into coloumns


df.T




0      1      2     3      4      5     6     7      8       9   \
Name     Tom  James  Ricky   Vin  Steve  Smith  Jack   Lee  David  Gasper   
Age       25     26     25    23     30     29    23    34     40      30   
Rating  4.23   3.24   3.98  2.56    3.2    4.6   3.8  3.78   2.98     4.8   

            10      11  
Name    Betina  Andres  
Age         51      46  
Rating     4.1    3.65

In [76]:
#Descriptive statsistics

data= {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack',
   'Lee','David','Gasper','Betina','Andres']),
   'Age':pd.Series([25,26,25,23,30,29,23,34,40,30,51,46]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,3.78,2.98,4.80,4.10,3.65])
}
df =pd.DataFrame(data)
df

Name  Age  Rating
0      Tom   25    4.23
1    James   26    3.24
2    Ricky   25    3.98
3      Vin   23    2.56
4    Steve   30    3.20
5    Smith   29    4.60
6     Jack   23    3.80
7      Lee   34    3.78
8    David   40    2.98
9   Gasper   30    4.80
10  Betina   51    4.10
11  Andres   46    3.65

In [77]:
#count -missing values wont count if its NAN means


df.count()

Name      12
Age       12
Rating    12
dtype: int64

In [78]:
#sum -sum everything give everything in a single call

df.sum()

Name      TomJamesRickyVinSteveSmithJackLeeDavidGasperBe...
Age                                                     382
Rating                                                44.92
dtype: object

In [79]:
#mean -Average values return


df.mean()

C:\Users\WIN10\AppData\Local\Temp/ipykernel_9688/2013933811.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


Age       31.833333
Rating     3.743333
dtype: float64

In [80]:
#median - return median value

df.median()

C:\Users\WIN10\AppData\Local\Temp/ipykernel_9688/2769215264.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median()


Age       29.50
Rating     3.79
dtype: float64

In [81]:
#mode -to find repeating values

df.mode()

Name   Age  Rating
0   Andres  23.0    2.56
1   Betina  25.0    2.98
2    David  30.0    3.20
3   Gasper   NaN    3.24
4     Jack   NaN    3.65
5    James   NaN    3.78
6      Lee   NaN    3.80
7    Ricky   NaN    3.98
8    Smith   NaN    4.10
9    Steve   NaN    4.23
10     Tom   NaN    4.60
11     Vin   NaN    4.80

In [82]:
#Standard diviasion 

df.std()

C:\Users\WIN10\AppData\Local\Temp/ipykernel_9688/455565929.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.std()


Age       9.232682
Rating    0.661628
dtype: float64

In [85]:
#min and max

#df.min()
df.max()

Name      Vin
Age        51
Rating    4.8
dtype: object

In [89]:
#absolute

df['Age'].abs()

0     25
1     26
2     25
3     23
4     30
5     29
6     23
7     34
8     40
9     30
10    51
11    46
Name: Age, dtype: int64

In [90]:
#prod() -product

df.prod()

C:\Users\WIN10\AppData\Local\Temp/ipykernel_9688/1256465122.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.prod()


Age       7.158408e+17
Rating    6.320128e+06
dtype: float64

In [91]:
#cumulative sum -df.cumsum() add each and every phreses

df.cumsum()

Name  Age  Rating
0                                                 Tom   25    4.23
1                                            TomJames   51    7.47
2                                       TomJamesRicky   76   11.45
3                                    TomJamesRickyVin   99   14.01
4                               TomJamesRickyVinSteve  129   17.21
5                          TomJamesRickyVinSteveSmith  158   21.81
6                      TomJamesRickyVinSteveSmithJack  181   25.61
7                   TomJamesRickyVinSteveSmithJackLee  215   29.39
8              TomJamesRickyVinSteveSmithJackLeeDavid  255   32.37
9        TomJamesRickyVinSteveSmithJackLeeDavidGasper  285   37.17
10  TomJamesRickyVinSteveSmithJackLeeDavidGasperBe...  336   41.27
11  TomJamesRickyVinSteveSmithJackLeeDavidGasperBe...  382   44.92

In [93]:
#cumlative product -str not working

df['Rating'].cumprod()

0     4.230000e+00
1     1.370520e+01
2     5.454670e+01
3     1.396395e+02
4     4.468465e+02
5     2.055494e+03
6     7.810877e+03
7     2.952512e+04
8     8.798485e+04
9     4.223273e+05
10    1.731542e+06
11    6.320128e+06
Name: Rating, dtype: float64

In [94]:
#describe -describe evertything

df.describe()

Age     Rating
count  12.000000  12.000000
mean   31.833333   3.743333
std     9.232682   0.661628
min    23.000000   2.560000
25%    25.000000   3.230000
50%    29.500000   3.790000
75%    35.500000   4.132500
max    51.000000   4.800000

In [96]:
#Function PIPE


#uses -apply complete data files at a time

data =np.random.randint(1,6,[4,3])
data


array([[2, 2, 3],
       [5, 1, 3],
       [1, 3, 2],
       [4, 4, 5]])

In [97]:
#supply data frame

df =pd.DataFrame(data =data,columns="col1 col2 col3".split())
df

col1  col2  col3
0     2     2     3
1     5     1     3
2     1     3     2
3     4     4     5

In [99]:
#By using functions we can manipulate datas and 



def add_numbers(first,last):
    return first + last
df.pipe(add_numbers,10)

col1  col2  col3
0    12    12    13
1    15    11    13
2    11    13    12
3    14    14    15

In [100]:
def subtracrt(first,last):
    return last-first
df.pipe(subtracrt,10)

col1  col2  col3
0     8     8     7
1     5     9     7
2     9     7     8
3     6     6     5

In [101]:
def subtracrt(first,last):
    return first-last
df.pipe(subtracrt,10)

col1  col2  col3
0    -8    -8    -7
1    -5    -9    -7
2    -9    -7    -8
3    -6    -6    -5

# FUNCTION APPLY METHODS

In [3]:
import pandas as pd
import numpy as np
data =np.random.randint(1,6,[4,3])
df =pd.DataFrame(data=data,columns="col1 col2 col3".split())
df

col1  col2  col3
0     2     5     2
1     5     4     4
2     2     4     4
3     1     5     3

In [4]:
#USER DEFINED FUNCTION

def double_number(num):
    return 2*num
df.apply(double_number)

col1  col2  col3
0     4    10     4
1    10     8     8
2     4     8     8
3     2    10     6

In [5]:
df.apply(double_number, axis = 1)


col1  col2  col3
0     4    10     4
1    10     8     8
2     4     8     8
3     2    10     6

In [6]:
df.apply(np.sum,axis=1)

0     9
1    13
2    10
3     9
dtype: int64

In [7]:
df

col1  col2  col3
0     2     5     2
1     5     4     4
2     2     4     4
3     1     5     3

In [8]:
df["col1"].apply(double_number)


0     4
1    10
2     4
3     2
Name: col1, dtype: int64

In [10]:
df.loc[2:2:]

col1  col2  col3
2     2     4     4

In [11]:
df.loc[2:2:].apply(double_number)

col1  col2  col3
2     4     8     8

# APPLY MAPS

In [12]:
import pandas as pd

import numpy as np

data =np.random.randint(1,6,[4,3])
data

array([[5, 5, 3],
       [3, 3, 3],
       [3, 1, 4],
       [3, 3, 3]])

In [15]:
df =pd.DataFrame(data)
df

0  1  2
0  5  5  3
1  3  3  3
2  3  1  4
3  3  3  3

In [16]:
df =pd.DataFrame(data=data,columns ="col1 col2 col3".split())
df

col1  col2  col3
0     5     5     3
1     3     3     3
2     3     1     4
3     3     3     3

In [ ]:
counter =0
def double_number(num):
    global cunter
    counter +=1
    return 2*num


In [19]:
counter =0
df.pipe(double_number)
counter

0